hugolini:
  cliente:
    endereco:
      url: http://localhost:8082/enderecos

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: hugolini-hexagonal
      username: root
      password: example